#! /bin/sh

# Launch the floating polybar
sh $HOME/.config/bspwm/scripts/polybarStart.sh &
# And the keyboard chortcuts manager
sxhkd &
# Set a wallpaper
feh --bg-fill `python ~/.config/tiny-theme-switcher/tiny-theme-switcher/main.py theme get --field wallpaper`
rm -rf $HOME/.fehbg
# Set the desktop cursor to be left-pointer
xsetroot -cursor_name left_ptr
# Setup a few workspaces
sh $HOME/.config/bspwm/scripts/workspaces.sh
# Start a compositor
picom &

# bspwm style
bspc config border_width         1
bspc config window_gap           5
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config border_radius 7

bspc config focused_border_color "#81a1c1"
bspc config normal_border_color "#2e3440"
bspc config active_border_color "#81a1c1"
bspc config presel_feedback_color "#3b4252"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config top_padding 0
