#! /bin/sh

sh $HOME/.config/bspwm/Scripts/polybarStart.sh &

sxhkd &

sh $HOME/.config/bspwm/Scripts/monitorBrightness.sh &

feh --bg-fill /home/$USER/.wallpapers/$(ls $HOME/.wallpapers| shuf -n 1) 
rm -rf /home/$USER/.fehbg

xsetroot -cursor_name left_ptr

sh $HOME/.config/bspwm/Scripts/workspaces.sh

picom &

amixer set Master toggle

bspc config border_width         1
bspc config window_gap           5
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config border_radius 7

bspc config focused_border_color "#81a1c1"
bspc config normal_border_color "#2e3440"
bspc config active_border_color "#81a1c1"
bspc config presel_feedback_color "#8fbcbb"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      false

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config top_padding 0

picom &
